import { Project, ParsedCell, IdeFile, ProjectType } from '../types';

// Configurable render widths (final on-page widths in px)
const CODE_RENDER_WIDTH = 350;   // width for code screenshots
const OUTPUT_RENDER_WIDTH = 350; // width for output/input/error screenshots
const DPI = 2;                   // device pixel ratio used for canvas (keep >1 for crispness)

export const generateWordDocument = async (project: Project) => {
  // Build HTML for Word document
  const htmlContent = await buildHtml(project);

  // Create Word-compatible blob and trigger download in browser
  const blob = new Blob(['\ufeff', htmlContent], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${project.name.replace(/\s+/g, '_')}_Report.doc`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

async function buildHtml(project: Project): Promise<string> {
  const headerDate = new Date().toLocaleDateString();

  let html = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head>
      <meta charset="utf-8">
      <title>${escapeHtml(project.name || '')}</title>
      <style>
        body { font-family: 'Calibri', 'Arial', sans-serif; background-color: #ffffff; color: #000000; line-height: 1.5; }
        .header { text-align: center; margin-bottom: 24pt; border-bottom: 2px solid #000; padding-bottom: 12pt; }
        .project-title { font-size: 18pt; font-weight: bold; color: #000; }
        .meta { font-size: 10pt; color: #444; margin-top: 4pt; }

        .student-info { margin: 20pt 0; padding: 12pt; border: 1px solid #000; background-color: #f9f9f9; }
        .info-row { margin: 8pt 0; display: flex; align-items: center; }
        .info-label { font-weight: bold; width: 120pt; display: inline-block; }
        .info-value { border-bottom: 1px solid #000; flex: 1; min-height: 20pt; display: inline-block; }

        .experiment-container { margin-bottom: 24pt; page-break-inside: avoid; }
        .section-label { font-size: 10pt; color: #000000; font-weight: bold; text-transform: uppercase; margin-top: 12pt; margin-bottom: 4pt; border-left: 4px solid #000; padding-left: 8pt; background: #e5e5e5; }

        .screenshot-container { margin: 8pt 0; text-align: center; page-break-inside: avoid; }

        /* Final on-page sizing for Word */
        .screenshot-img { max-width: 100%; width: ${CODE_RENDER_WIDTH}px; height: auto; border: 1px solid #ccc; display: block; margin: 0 auto; }
        .screenshot-img-output { max-width: 100%; width: ${OUTPUT_RENDER_WIDTH}px; height: auto; border: 1px solid #ccc; display: block; margin: 0 auto; }

        h3 { font-size: 14pt; color: #000; border-bottom: 1px solid #000; padding-bottom: 4pt; margin-bottom: 8pt; font-weight: bold; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="project-title">${escapeHtml(project.name || '')}</div>
        <div class="meta">Generated by AutolabDocs • ${headerDate}</div>
      </div>

      <div class="student-info">
        <div class="info-row"><span class="info-label">Name:</span><span class="info-value">&nbsp;</span></div>
        <div class="info-row"><span class="info-label">Roll Number:</span><span class="info-value">&nbsp;</span></div>
        <div class="info-row"><span class="info-label">Date:</span><span class="info-value">&nbsp;</span></div>
      </div>
  `;

  // Notebook (Colab-like) handling
  if (project.type === ProjectType.COLAB && project.notebookContent) {
    const cells = project.notebookContent as ParsedCell[];
    for (let i = 0; i < cells.length; i++) {
      const cell = cells[i];
      if (cell.type === 'code') {
        html += `\n      <div class="experiment-container">\n        <div class="section-label">Code Cell [${cell.executionCount ?? i}]</div>\n        <div class="screenshot-container">\n          <img src="${await generateCodeScreenshot(cell.content)}" class="screenshot-img" />\n        </div>\n        `;

        if (cell.outputs && cell.outputs.length > 0) {
          html += `<div class="section-label">Output</div>`;
        }

        if (cell.outputs) {
          for (const out of cell.outputs) {
            if (out.type === 'text') {
              html += `\n            <div class="screenshot-container">\n              <img src="${await generateOutputScreenshot(stripAnsi(out.data as string), 'output')}" class="screenshot-img-output" />\n            </div>`;
            } else if (out.type === 'image') {
              html += `\n            <div class="screenshot-container">\n              <img src="data:${out.mimeType};base64,${out.data}" class="screenshot-img-output" />\n            </div>`;
            } else if (out.type === 'error') {
              html += `\n            <div class="screenshot-container">\n              <img src="${await generateOutputScreenshot(out.data as string, 'error')}" class="screenshot-img-output" />\n            </div>`;
            }
          }
        }

        html += `\n      </div>`;
      }
    }
  }

  // IDE / Files handling
  else if (project.type === ProjectType.IDE && project.files) {
    const files = project.files as IdeFile[];
    for (let i = 0; i < files.length; i++) {
      const file = files[i];
      html += `\n      <div class="experiment-container">\n        <h3>Experiment ${i + 1}: ${escapeHtml(file.name)}</h3>\n\n        <div class="section-label">Source Code</div>\n        <div class="screenshot-container">\n          <img src="${await generateCodeScreenshot(file.content)}" class="screenshot-img" />\n        </div>\n      `;

      if (file.lastInput) {
        html += `\n        <div class="section-label">Standard Input</div>\n        <div class="screenshot-container">\n          <img src="${await generateOutputScreenshot(stripAnsi(file.lastInput), 'input')}" class="screenshot-img-output" />\n        </div>\n        `;
      }

      html += `\n        <div class="section-label">Execution Output</div>\n        <div class="screenshot-container">\n          <img src="${await generateOutputScreenshot(file.lastOutput ? stripAnsi(file.lastOutput) : 'No output recorded', 'output')}" class="screenshot-img-output" />\n        </div>\n      `;

      if (file.lastError) {
        html += `\n        <div class="section-label">Error Trace</div>\n        <div class="screenshot-container">\n          <img src="${await generateOutputScreenshot(file.lastError, 'error')}" class="screenshot-img-output" />\n        </div>\n        `;
      }

      html += `\n      </div>`;
    }
  }

  html += `\n    </body>\n    </html>`;

  return html;
}

// --- Screenshot generators ---
export const generateCodeScreenshot = async (code: string): Promise<string> => {
  const padding = 12;
  const fontSize = 11;
  const lineHeight = 17;
  const lineNumberWidth = 40;
  const charWidth = 7.0;

  const contentArea = CODE_RENDER_WIDTH - lineNumberWidth - padding * 2;
  const maxCharsPerLine = Math.max(20, Math.floor(contentArea / charWidth));

  const rawLines = (code || '').split('\n');
  const wrappedLines: Array<{ text: string; isWrapped: boolean; originalIndex: number }> = [];

  rawLines.forEach((line, idx) => {
    if (line.length <= maxCharsPerLine) {
      wrappedLines.push({ text: line, isWrapped: false, originalIndex: idx });
    } else {
      let remaining = line;
      let first = true;
      while (remaining.length > 0) {
        const chunk = remaining.substring(0, maxCharsPerLine);
        wrappedLines.push({ text: chunk, isWrapped: !first, originalIndex: idx });
        remaining = remaining.substring(maxCharsPerLine);
        first = false;
      }
    }
  });

  const totalLines = Math.max(1, wrappedLines.length);
  const width = CODE_RENDER_WIDTH;
  const height = Math.min(2000, (totalLines * lineHeight) + padding * 2 + 8);

  const canvas = document.createElement('canvas');
  const ctx = canvas.getContext('2d');
  if (!ctx) return '';

  canvas.width = Math.round(width * DPI);
  canvas.height = Math.round(height * DPI);
  canvas.style.width = width + 'px';
  canvas.style.height = height + 'px';
  ctx.scale(DPI, DPI);

  // Background & border
  ctx.fillStyle = '#1e1e1e';
  ctx.fillRect(0, 0, width, height);
  ctx.strokeStyle = '#3e3e42';
  ctx.lineWidth = 1;
  ctx.strokeRect(0, 0, width, height);

  // Line numbers background
  ctx.fillStyle = '#252526';
  ctx.fillRect(0, 0, lineNumberWidth, height);

  // Separator
  ctx.strokeStyle = '#3e3e42';
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(lineNumberWidth, 0);
  ctx.lineTo(lineNumberWidth, height);
  ctx.stroke();

  ctx.font = `${fontSize}px "SF Mono", Monaco, "Cascadia Code", "Consolas", monospace`;
  ctx.textBaseline = 'top';

  wrappedLines.forEach((lineObj, i) => {
    const y = padding + (i * lineHeight);
    const line = lineObj.text;

    // Line number
    ctx.textAlign = 'right';
    ctx.fillStyle = '#858585';
    if (!lineObj.isWrapped) {
      ctx.fillText(String(lineObj.originalIndex + 1), lineNumberWidth - 8, y + 2);
    } else {
      ctx.fillText('↳', lineNumberWidth - 8, y + 2);
    }

    // Syntax-ish coloring
    ctx.textAlign = 'left';
    const trimmed = line.trim();
    if (trimmed.startsWith('#') || trimmed.startsWith('//')) {
      ctx.fillStyle = '#6a9955';
    } else if (trimmed.match(/^(import|from|include|using|def|class|function|const|let|var|public|private|protected)\s/)) {
      ctx.fillStyle = '#c586c0';
    } else if (trimmed.match(/(int|void|return|cout|print|printf|scanf|if|else|for|while|do|switch|case)\s/)) {
      ctx.fillStyle = '#569cd6';
    } else if (trimmed.match(/[\"\'].*[\"\']/)) {
      ctx.fillStyle = '#ce9178';
    } else {
      ctx.fillStyle = '#d4d4d4';
    }

    ctx.fillText(line, lineNumberWidth + 8, y + 2);
  });

  return canvas.toDataURL('image/png');
};

export const generateOutputScreenshot = async (text: string, type: 'output' | 'input' | 'error'): Promise<string> => {
  const padding = 12;
  const fontSize = 11;
  const lineHeight = 16;
  const charWidth = 7.0;

  const contentArea = OUTPUT_RENDER_WIDTH - padding * 2;
  const maxCharsPerLine = Math.max(30, Math.floor(contentArea / charWidth));

  const rawLines = (text || '').split('\n');
  const wrappedLines: string[] = [];
  rawLines.forEach(line => {
    if (line.length <= maxCharsPerLine) {
      wrappedLines.push(line);
    } else {
      let remaining = line;
      while (remaining.length > 0) {
        wrappedLines.push(remaining.substring(0, maxCharsPerLine));
        remaining = remaining.substring(maxCharsPerLine);
      }
    }
  });

  const totalLines = Math.max(1, wrappedLines.length);
  const width = OUTPUT_RENDER_WIDTH;
  const height = Math.min(2000, (totalLines * lineHeight) + padding * 2 + 8);

  const canvas = document.createElement('canvas');
  const ctx = canvas.getContext('2d');
  if (!ctx) return '';

  canvas.width = Math.round(width * DPI);
  canvas.height = Math.round(height * DPI);
  canvas.style.width = width + 'px';
  canvas.style.height = height + 'px';
  ctx.scale(DPI, DPI);

  // Colors by type
  let bgColor = '#0e0e0e';
  let borderColor = '#007acc';
  let textColor = '#cccccc';
  if (type === 'error') {
    bgColor = '#2d0a0a';
    borderColor = '#f14c4c';
    textColor = '#f48771';
  } else if (type === 'input') {
    bgColor = '#1a1a2e';
    borderColor = '#9d4edd';
    textColor = '#e0aaff';
  }

  ctx.fillStyle = bgColor;
  ctx.fillRect(0, 0, width, height);

  ctx.strokeStyle = borderColor;
  ctx.lineWidth = 3;
  ctx.strokeRect(0, 0, width, height);

  ctx.fillStyle = borderColor;
  ctx.fillRect(0, 0, 4, height);

  ctx.fillStyle = textColor;
  ctx.font = `${fontSize}px "SF Mono", Monaco, "Cascadia Code", "Consolas", monospace`;
  ctx.textBaseline = 'top';

  wrappedLines.forEach((line, i) => {
    const y = padding + (i * lineHeight);
    ctx.fillText(line, padding + 6, y + 1);
  });

  return canvas.toDataURL('image/png');
};

// --- Utilities ---
export const stripAnsi = (str: string): string => {
  if (!str) return '';
  return str
    .replace(/\x1b\]0;[\s\S]*?(\x07|\x1b\\)/g, '')
    .replace(/\x1b\[[0-9;]*[a-zA-Z]/g, '')
    .replace(/\x1b\[\?[\d;]*[a-z]/g, '')
    .replace(/\x1bO[A-Za-z]/g, '')
    .replace(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g, '')
    .trim();
};

export const escapeHtml = (unsafe: string): string => {
  if (!unsafe) return '';
  return String(unsafe)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
};
