"use client"

import type React from "react"
import { X, Download, FileText, Code2, Zap } from "lucide-react"
import { CellOutput } from "../types"

// Types to match both IDE and Colab workspace structures
export interface PreviewFile {
  name: string
  content: string
  lastInput?: string
  lastOutput?: string
  outputs?: CellOutput[]
  type?: "code" | "markdown"
}

interface PreviewModalProps {
  title: string
  files: PreviewFile[]
  onClose: () => void
  onDownload?: () => void
}

export const PreviewModal: React.FC<PreviewModalProps> = ({ title, files, onClose, onDownload }) => {
  const currentDate = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });

  return (
    <div className="fixed inset-0 z-[100] bg-black/95 backdrop-blur-xl flex flex-col items-center justify-center p-4 md:p-6 animate-in fade-in duration-300">
      
      {/* Modal Toolbar */}
      <div className="w-full max-w-4xl flex items-center justify-between mb-4 px-2">
        <div>
          <h3 className="text-lg font-bold text-white tracking-tight">Document Preview</h3>
          <p className="text-xs text-zinc-500">
             Generated • {files.length} items
          </p>
        </div>
        <div className="flex items-center gap-3">
           {onDownload && (
            <button
              onClick={onDownload}
              className="px-5 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg font-medium text-sm flex items-center gap-2 transition-all shadow-lg shadow-blue-500/20"
            >
              <Download size={16} />
              Export .DOCX
            </button>
          )}
          <button
            onClick={onClose}
            className="p-2 text-zinc-400 hover:text-white hover:bg-white/[0.1] rounded-lg transition-all"
          >
            <X size={20} />
          </button>
        </div>
      </div>

      {/* Document Viewport - Scrollable */}
      <div className="relative w-full flex-1 overflow-y-auto overflow-x-hidden flex justify-center scrollbar-thin scrollbar-thumb-zinc-700 scrollbar-track-transparent pb-8">
        
        {/* A4 Page Simulation */}
        <div className="w-full max-w-[210mm] bg-white text-black shadow-2xl min-h-full p-[20mm] box-border animate-in slide-in-from-bottom-8 duration-500 origin-top">
          
          {/* Document Header */}
          <div className="border-b-2 border-black pb-4 mb-8 text-center">
            <h1 className="text-2xl font-bold uppercase tracking-wide mb-2">{title}</h1>
            <p className="text-sm text-gray-600">Generated by AutolabDocs • {currentDate}</p>
          </div>

           {/* Student Info Placeholder (mimics exportService) */}
           <div className="mb-8 p-4 bg-gray-50 border border-gray-300 text-sm">
             <div className="grid grid-cols-[100px_1fr] gap-y-2 mb-2">
               <span className="font-bold">Name:</span>
               <div className="border-b border-gray-400"></div>
             </div>
             <div className="grid grid-cols-[100px_1fr] gap-y-2 mb-2">
               <span className="font-bold">Roll Number:</span>
               <div className="border-b border-gray-400"></div>
             </div>
             <div className="grid grid-cols-[100px_1fr] gap-y-2">
               <span className="font-bold">Date:</span>
               <div className="border-b border-gray-400"></div>
             </div>
           </div>

          {/* Content Items */}
          <div className="space-y-8">
            {files.map((file, index) => {
              const isMarkdown = file.type === "markdown"
              
              return (
                <div key={index} className="break-inside-avoid mb-8">
                   {/* Item Header */}
                   <div className="bg-gray-200 border-l-4 border-black px-3 py-2 mb-4">
                     <h2 className="text-sm font-bold uppercase tracking-wider flex items-center gap-2">
                       {isMarkdown ? <FileText size={14} /> : <Code2 size={14} />}
                       {isMarkdown ? "Documentation" : `Code Cell [${index + 1}]`}
                     </h2>
                   </div>

                  {/* Content Body */}
                  <div className="mb-4">
                    {/* Source Code / Markdown */}
                    {isMarkdown ? (
                       <div className="prose prose-sm max-w-none text-gray-800 whitespace-pre-wrap font-serif">
                         {file.content}
                       </div>
                    ) : (
                      <div className="border border-gray-300 bg-gray-50 p-3 rounded-sm mb-4">
                         <div className="text-[10px] text-gray-500 font-bold uppercase tracking-wider mb-1">Source Code</div>
                         <pre className="text-xs font-mono text-gray-800 whitespace-pre-wrap break-words overflow-x-hidden">
                           {file.content}
                         </pre>
                      </div>
                    )}
                  </div>

                  {/* Execution Info (Output) */}
                  {(file.lastInput || file.lastOutput || (file.outputs && file.outputs.length > 0)) && (
                    <div className="mt-4 space-y-4">
                      {file.lastInput && (
                        <div className="border border-gray-300 p-3 bg-white">
                           <div className="text-[10px] text-gray-500 font-bold uppercase tracking-wider mb-1">Input</div>
                           <pre className="text-xs font-mono text-gray-600 whitespace-pre-wrap">{file.lastInput}</pre>
                        </div>
                      )}
                      
                      {/* Rich outputs */}
                      {(file.outputs && file.outputs.length > 0) ? (
                        <div>
                           <div className="text-xs font-bold uppercase tracking-wider border-b border-gray-300 pb-1 mb-2 flex items-center gap-1">
                             <Zap size={12} /> Output
                           </div>
                           <div className="space-y-4">
                            {file.outputs.map((output, idx) => (
                              <div key={idx} className="border border-gray-200 p-2 bg-white flex justify-center">
                                 {output.type === "image" && (
                                    <img
                                      src={`data:${output.mimeType};base64,${output.data}`}
                                      alt="Output"
                                      className="max-w-full h-auto block"
                                    />
                                  )}

                                  {output.type === "text" && (
                                    <pre className="text-xs font-mono text-gray-800 whitespace-pre-wrap w-full">
                                      {output.data}
                                    </pre>
                                  )}

                                  {output.type === "error" && (
                                    <div className="w-full p-2 bg-red-50 border-l-2 border-red-500 text-red-800 text-xs font-mono whitespace-pre-wrap">
                                      {output.data}
                                    </div>
                                  )}

                                  {output.type === "html" && (
                                    <div
                                      className="prose prose-sm max-w-none w-full"
                                      dangerouslySetInnerHTML={{ __html: output.data as string }}
                                    />
                                  )}
                              </div>
                            ))}
                          </div>
                        </div>
                      ) : file.lastOutput && (
                        <div>
                          <div className="text-xs font-bold uppercase tracking-wider border-b border-gray-300 pb-1 mb-2 flex items-center gap-1">
                             <Zap size={12} /> Output
                           </div>
                          <div className="border border-gray-300 p-3 bg-white">
                            <pre className="text-xs font-mono text-gray-800 whitespace-pre-wrap">{file.lastOutput}</pre>
                          </div>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              )
            })}
          </div>

          {/* Page Footer Simulation */}
          <div className="mt-12 pt-4 border-t border-gray-300 text-center text-xs text-gray-400">
             Page 1 of 1
          </div>
        </div>
      </div>
    </div>
  )
}
